export const businessType = [
    { value: "", text: "Please Select Type of F&B Business" },
    { value: "cafe", text: "Cafe" },
    { value: "kopitiam", text: "Kopitiam" },
    { value: "bar and pub", text: "Bar and Pub" },
    { value: "fast food restaurant", text: "Fast Food Restaurant" },
    { value: "food truck", text: "Food Truck" },
    { value: "bakery", text: "Bakery" },
    { value: "catering service", text: "Catering Service" },
    { value: "food delivery service", text: "Food Delivery Service" },
    { value: "buffet", text: "Buffet" },
    { value: "specialty food store", text: "Specialty Food Store" },
    { value: "breweries and wineries", text: "Breweries and Wineries" },
    { value: "ice cream parlor", text: "Ice Cream Parlor" },
    { value: "juice bar", text: "Juice Bar" },
    { value: "food court", text: "Food Court" },
    { value: "fine dining restaurant", text: "Fine Dining Restaurant" },
    { value: "food hall", text: "Food Hall" },
    { value: "ethnic restaurant", text: "Ethnic Restaurant" },
    { value: "hotel restaurant", text: "Hotel Restaurant" },
    { value: "brewpub", text: "Brewpub" },
    { value: "tea room", text: "Tea Room" },
    { value: "delicatessen", text: "Delicatessen" },
    {
        value: "vegan or vegetarian restaurant",
        text: "Vegan/Vegetarian Restaurant",
    },
    { value: "sushi bar", text: "Sushi Bar" },
];

export const cuisineType = [
    { value: "italian", text: "Italian Cuisine" },
    { value: "chinese", text: "Chinese Cuisine" },
    { value: "mexican", text: "Mexican Cuisine" },
    { value: "indian", text: "Indian Cuisine" },
    { value: "japanese", text: "Japanese Cuisine" },
    { value: "french", text: "French Cuisine" },
    { value: "thai", text: "Thai Cuisine" },
    { value: "spanish", text: "Spanish Cuisine" },
    { value: "greek", text: "Greek Cuisine" },
    { value: "lebanese", text: "Lebanese Cuisine" },
    { value: "turkish", text: "Turkish Cuisine" },
    { value: "korean", text: "Korean Cuisine" },
    { value: "moroccan", text: "Moroccan Cuisine" },
    { value: "vietnamese", text: "Vietnamese Cuisine" },
    { value: "brazilian", text: "Brazilian Cuisine" },
    { value: "american", text: "American Cuisine" },
    { value: "british", text: "British Cuisine" },
    { value: "ethiopian", text: "Ethiopian Cuisine" },
    { value: "russian", text: "Russian Cuisine" },
    { value: "indonesian", text: "Indonesian Cuisine" },
    { value: "german", text: "German Cuisine" },
    { value: "caribbean", text: "Caribbean Cuisine" },
    { value: "peruvian", text: "Peruvian Cuisine" },
    { value: "middle_eastern", text: "Middle Eastern Cuisine" },
    { value: "south_african", text: "South African Cuisine" },
    { value: "malaysian", text: "Malaysian Cuisine" },
    { value: "argentinian", text: "Argentinian Cuisine" },
    { value: "swedish", text: "Swedish Cuisine" },
    { value: "australian", text: "Australian Cuisine" },
    { value: "portuguese", text: "Portuguese Cuisine" },
];

export const recipeCategories = [
    { value: "", text: "Please Select Category of Recipe" },
    { value: "appetizers", text: "Appetizers" },
    { value: "soups", text: "Soups" },
    { value: "salads", text: "Salads" },
    { value: "sandwiches", text: "Sandwiches" },
    { value: "burgers", text: "Burgers" },
    { value: "pizzas", text: "Pizzas" },
    { value: "pasta", text: "Pasta" },
    { value: "seafood", text: "Seafood" },
    { value: "steaks", text: "Steaks" },
    { value: "chicken dishes", text: "Chicken dishes" },
    { value: "vegetarian dishes", text: "Vegetarian dishes" },
    { value: "sushi", text: "Sushi" },
    { value: "tacos", text: "Tacos" },
    { value: "burritos", text: "Burritos" },
    { value: "wraps", text: "Wraps" },
    { value: "stir-fry", text: "Stir-fry" },
    { value: "rice", text: "Rice" },
    { value: "noodle", text: "Noodle" },
    { value: "barbecue", text: "Barbecue" },
    { value: "ribs", text: "Ribs" },
    { value: "wings", text: "Wings" },
    { value: "hot dogs", text: "Hot dogs" },
    { value: "fried chicken", text: "Fried chicken" },
    { value: "omelettes", text: "Omelettes" },
    { value: "deserts", text: "deserts" },
    { value: "sandwiches", text: "Sandwiches" },
    { value: "bread", text: "Bread" },
    { value: "pies", text: "Pies" },
    { value: "lasagna", text: "Lasagna" },
    { value: "ramen", text: "Ramen" },
    { value: "other", text: "Others" },
];
