export const businessType = [
    { value: "", text: "Please Select Type of F&B Business" },
    { value: "cafe", text: "Cafe" },
    { value: "kopitiam", text: "Kopitiam" },
    { value: "bar and pub", text: "Bar and Pub" },
    { value: "fast food restaurant", text: "Fast Food Restaurant" },
    { value: "food truck", text: "Food Truck" },
    { value: "bakery", text: "Bakery" },
    { value: "catering service", text: "Catering Service" },
    { value: "food delivery service", text: "Food Delivery Service" },
    { value: "buffet", text: "Buffet" },
    { value: "specialty food store", text: "Specialty Food Store" },
    { value: "breweries and wineries", text: "Breweries and Wineries" },
    { value: "ice cream parlor", text: "Ice Cream Parlor" },
    { value: "juice bar", text: "Juice Bar" },
    { value: "food court", text: "Food Court" },
    { value: "fine dining restaurant", text: "Fine Dining Restaurant" },
    { value: "food hall", text: "Food Hall" },
    { value: "ethnic restaurant", text: "Ethnic Restaurant" },
    { value: "hotel restaurant", text: "Hotel Restaurant" },
    { value: "brewpub", text: "Brewpub" },
    { value: "tea room", text: "Tea Room" },
    { value: "delicatessen", text: "Delicatessen" },
    {
        value: "vegan or vegetarian restaurant",
        text: "Vegan/Vegetarian Restaurant",
    },
    { value: "sushi bar", text: "Sushi Bar" },
];

export const cuisineType = [
    { value: "italian", text: "Italian Cuisine" },
    { value: "chinese", text: "Chinese Cuisine" },
    { value: "mexican", text: "Mexican Cuisine" },
    { value: "indian", text: "Indian Cuisine" },
    { value: "japanese", text: "Japanese Cuisine" },
    { value: "french", text: "French Cuisine" },
    { value: "thai", text: "Thai Cuisine" },
    { value: "spanish", text: "Spanish Cuisine" },
    { value: "greek", text: "Greek Cuisine" },
    { value: "lebanese", text: "Lebanese Cuisine" },
    { value: "turkish", text: "Turkish Cuisine" },
    { value: "korean", text: "Korean Cuisine" },
    { value: "moroccan", text: "Moroccan Cuisine" },
    { value: "vietnamese", text: "Vietnamese Cuisine" },
    { value: "brazilian", text: "Brazilian Cuisine" },
    { value: "american", text: "American Cuisine" },
    { value: "british", text: "British Cuisine" },
    { value: "ethiopian", text: "Ethiopian Cuisine" },
    { value: "russian", text: "Russian Cuisine" },
    { value: "indonesian", text: "Indonesian Cuisine" },
    { value: "german", text: "German Cuisine" },
    { value: "caribbean", text: "Caribbean Cuisine" },
    { value: "peruvian", text: "Peruvian Cuisine" },
    { value: "middle_eastern", text: "Middle Eastern Cuisine" },
    { value: "south_african", text: "South African Cuisine" },
    { value: "malaysian", text: "Malaysian Cuisine" },
    { value: "argentinian", text: "Argentinian Cuisine" },
    { value: "swedish", text: "Swedish Cuisine" },
    { value: "australian", text: "Australian Cuisine" },
    { value: "portuguese", text: "Portuguese Cuisine" },
];

export const recipeCategories = [
    { value: "", text: "Please Select Category of Recipe" },
    { value: "appetizers", text: "Appetizers" },
    { value: "soups", text: "Soups" },
    { value: "salads", text: "Salads" },
    { value: "sandwiches", text: "Sandwiches" },
    { value: "burgers", text: "Burgers" },
    { value: "pizzas", text: "Pizzas" },
    { value: "pasta", text: "Pasta" },
    { value: "seafood", text: "Seafood" },
    { value: "steaks", text: "Steaks" },
    { value: "chicken dishes", text: "Chicken dishes" },
    { value: "vegetarian dishes", text: "Vegetarian dishes" },
    { value: "sushi", text: "Sushi" },
    { value: "tacos", text: "Tacos" },
    { value: "burritos", text: "Burritos" },
    { value: "wraps", text: "Wraps" },
    { value: "stir-fry", text: "Stir-fry" },
    { value: "rice", text: "Rice" },
    { value: "noodle", text: "Noodle" },
    { value: "barbecue", text: "Barbecue" },
    { value: "ribs", text: "Ribs" },
    { value: "wings", text: "Wings" },
    { value: "hot dogs", text: "Hot dogs" },
    { value: "fried chicken", text: "Fried chicken" },
    { value: "omelettes", text: "Omelettes" },
    { value: "deserts", text: "deserts" },
    { value: "sandwiches", text: "Sandwiches" },
    { value: "bread", text: "Bread" },
    { value: "pies", text: "Pies" },
    { value: "lasagna", text: "Lasagna" },
    { value: "ramen", text: "Ramen" },
    { value: "other", text: "Others" },
];

export const menuTypes = [
    { value: "drinks", text: "Drinks Menu" },
    { value: "appetizer", text: "Appetizer Menu" },
    { value: "maincourse", text: "Main Course Menu" },
    { value: "dessert", text: "Dessert Menu" },
    { value: "happyhour", text: "Happy Hour Menu" },
    { value: "breakfast", text: "Breakfast Menu" },
    { value: "lunch", text: "Lunch Menu" },
    { value: "dinner", text: "Dinner Menu" },
    { value: "brunch", text: "Brunch Menu" },
    { value: "buffet", text: "Buffet Menu" },
    { value: "kids", text: "Kids Menu" },
    { value: "takeaway", text: "Takeaway Menu" },
    { value: "catering", text: "Catering Menu" },
    { value: "chefspecials", text: "Chef's Specials Menu" },
    { value: "seasonal", text: "Seasonal Menu" },
    { value: "tasting", text: "Tasting Menu" },
    { value: "tapas", text: "Tapas Menu" },
    { value: "winelist", text: "Wine List" },
    { value: "beer", text: "Beer Menu" },
    { value: "cocktail", text: "Cocktail Menu" },
    { value: "mocktail", text: "Mocktail Menu" },
    { value: "juicebar", text: "Juice Bar Menu" },
    { value: "smoothie", text: "Smoothie Menu" },
    { value: "milkshake", text: "Milkshake Menu" },
    { value: "coffee", text: "Coffee Menu" },
    { value: "tea", text: "Tea Menu" },
    { value: "icecream", text: "Ice Cream Menu" },
    { value: "milktea", text: "Milk Tea Menu" },
    { value: "pizza", text: "Pizza Menu" },
    { value: "burger", text: "Burger Menu" },
    { value: "sandwich", text: "Sandwich Menu" },
    { value: "pasta", text: "Pasta Menu" },
    { value: "salad", text: "Salad Menu" },
    { value: "seafood", text: "Seafood Menu" },
    { value: "vegetarian", text: "Vegetarian Menu" },
    { value: "glutenfree", text: "Gluten-Free Menu" },
    { value: "vegan", text: "Vegan Menu" },
    { value: "lowcalorie", text: "Low-Calorie Menu" },
    { value: "allergenfree", text: "Allergen-Free Menu" },
    { value: "customizable", text: "Customizable Menu" },
];

export const priorityChoices = [
    { value: "", text: "Please Select level of Priority" },
    { value: "1", text: "Very Low" },
    { value: "2", text: "Low" },
    { value: "3", text: "Medium" },
    { value: "4", text: "High" },
    { value: "5", text: "Very High" },
];

export const planType = [
    { value: "", text: "Please Select Business Growth Plan Type" },
    { value: "FD", text: "Food Delivery Marketplace Strategy" },
    { value: "OE", text: "Outlet Expansion Strategy" },
    { value: "MK", text: "Marketing Strategy" },
]

export const hiringMethods = [
    { value: "", text: "Please Select Hiring Method"},
    { value: "direct", text: "Direct Application"},
    { value: "online", text: "Online Job Platform"},
    { value: "referral", text: "Employee Referral"},
    { value: "agency", text: "Job Agency"},
    { value: "socialMedia", text: "Social Media Hiring"},
    { value: "transfer", text: "Transfer From Existing Outlet"},
]

export const position = [
    { value: "", text: "Please Select Position"},
    { value: "service", text: "Service Staff"},
    { value: "kitchen", text: "Kitchen Staff"},
    { value: "supervisor", text: "Supervisor"},
    { value: "assistant", text: "Assistant Manager"},
    { value: "manager", text: "Manager"},
]